JUnit5対応
nablarch/nablarch-testing-junit5 pull request #2
Opened 2022-01-20 07:00 UTC by opengl-8080

テストの方法について補足。

- `<クラス名>Test` は単体テスト、 `<クラス名>IntegrationTest` は結合テスト
  - 単体テスト = テスト対象を直接 new して、個別のメソッド単位で動かしてのテスト
  - 結合テスト = 実際に JUnit 5 上でメタアノテーションを使ってサポートクラスの生成・インジェクションが動いていることの確認
- 結合テストで JUnit5 が必要になるので、単体テストも全て JUnit5 で記述しています

2022-01-20 10:34 UTC, kumagoro1202 requested changes

2022-01-20 10:34 UTC, kumagoro1202 commented on pom.xml
> +      <version>5.8.2</version>
bom入れてるので不要では？

2022-01-20 23:45 UTC, opengl-8080 commented on pom.xml
> +      <version>5.8.2</version>
https://github.com/nablarch/nablarch-testing-junit5/pull/2/commits/5a0738c174531a4b4772c30aec3464f674d8a35d

たしかに。
バージョンの記述を削除しました。

2022-01-21 04:29 UTC, kumagoro1202 approved these changes

2022-01-21 04:29 UTC, merged